//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int DisplayID { get; set; }
        public System.Guid ConditionUID { get; set; }
        public System.Guid EntityUID { get; set; }
        public System.Guid SetUID { get; set; }
        public byte ConditionType { get; set; }
        public Nullable<System.Guid> ReferenceUID { get; set; }
        public Nullable<byte> DateInterval { get; set; }
        public Nullable<byte> PrimaryFrequency { get; set; }
        public Nullable<byte> SecondaryFrequency { get; set; }
        public bool OncePerDay { get; set; }
        public Nullable<System.DateTime> AfterTimeUtc { get; set; }
        public Nullable<System.DateTime> BeforeTimeUtc { get; set; }
        public bool UseLocal { get; set; }
        public string Directory { get; set; }
        public string FileExists { get; set; }
        public Nullable<byte> PackageType { get; set; }
        public Nullable<int> ProcessDateModifier { get; set; }
        public bool IsNegative { get; set; }
        public bool IsLive { get; set; }
    }
}
