//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionSet
    {
        public int DisplayID { get; set; }
        public System.Guid SetUID { get; set; }
        public System.Guid EntityUID { get; set; }
        public Nullable<System.Guid> ParentSet { get; set; }
        public byte Matching { get; set; }
        public bool IsNegative { get; set; }
        public bool IsLive { get; set; }
    }
}
