//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionModule
    {
        public System.Guid ModuleUID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleAssembly { get; set; }
        public string ModuleObject { get; set; }
        public int Controls { get; set; }
    }
}
