//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCondition
    {
        public System.Guid GlobalUID { get; set; }
        public string ConditionName { get; set; }
    }
}
