//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportValidation_bad20120916
    {
        public System.Guid ValidationUID { get; set; }
        public string ServerName { get; set; }
        public string Catelog { get; set; }
        public string TableName { get; set; }
        public long LastImportCount { get; set; }
        public System.DateTime LastImportedUtc { get; set; }
    }
}
