//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportErrorGroup
    {
        public System.Guid GroupUID { get; set; }
        public System.Guid StepUID { get; set; }
        public System.Guid InstanceUID { get; set; }
        public string Line { get; set; }
        public byte FailedAt { get; set; }
        public System.DateTime LoggedAtUtc { get; set; }
    }
}
