//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexArchive
    {
        public System.Guid IndexUID { get; set; }
        public string Server { get; set; }
        public string Catelog { get; set; }
        public string Entity { get; set; }
        public string IndexName { get; set; }
        public string IndexDesc { get; set; }
        public string IndexFields { get; set; }
    }
}
