//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public System.Guid JobUID { get; set; }
        public int DisplayID { get; set; }
        public string JobName { get; set; }
        public byte Style { get; set; }
        public Nullable<System.Guid> Category { get; set; }
        public bool RequiresVerification { get; set; }
        public byte Priority { get; set; }
        public short Weight { get; set; }
        public int Controls { get; set; }
        public Nullable<System.Guid> StartStep { get; set; }
        public byte Frequency { get; set; }
        public int Interval { get; set; }
        public System.DateTime StopAtUtc { get; set; }
        public int ArchiveAfter { get; set; }
        public byte ServiceLevel { get; set; }
        public int ServiceDuration { get; set; }
        public byte AlertSeverity { get; set; }
        public string Note { get; set; }
        public string HelpFile { get; set; }
        public Nullable<System.DateTime> LastArchiveUtc { get; set; }
        public Nullable<System.DateTime> LastOccurenceUtc { get; set; }
        public bool IsLive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
