//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInformation
    {
        public bool IsLive { get; set; }
        public int DisplayID { get; set; }
        public string JobName { get; set; }
        public string CategoryName { get; set; }
        public string StepName { get; set; }
        public string ConfigurationFile { get; set; }
        public string ModuleName { get; set; }
        public string ModuleObject { get; set; }
    }
}
