//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStep
    {
        public int DisplayID { get; set; }
        public System.Guid StepUID { get; set; }
        public System.Guid JobUID { get; set; }
        public string StepName { get; set; }
        public System.Guid ModuleUID { get; set; }
        public Nullable<System.Guid> OnSuccess { get; set; }
        public Nullable<System.Guid> OnFailure { get; set; }
        public bool CanRestart { get; set; }
        public bool IsLive { get; set; }
        public bool IsDeleted { get; set; }
        public string ConfigurationFile { get; set; }
        public string HelpFile { get; set; }
    }
}
