//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTimeDuration
    {
        public string Job__Category_ { get; set; }
        public Nullable<System.DateTime> StartedOnUtc { get; set; }
        public Nullable<System.DateTime> CompletedOnUtc { get; set; }
        public Nullable<int> Duration_in_Secs { get; set; }
    }
}
