//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVersion
    {
        public System.Guid ChangeUID { get; set; }
        public System.Guid JobUID { get; set; }
        public System.Guid ChangedBy { get; set; }
        public string FromMachine { get; set; }
        public System.DateTime ChangedAtUtc { get; set; }
        public byte EventType { get; set; }
        public string EventDetail { get; set; }
    }
}
