//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public int KeywordID { get; set; }
        public System.Guid KeywordUID { get; set; }
        public System.Guid CategoryUID { get; set; }
        public string Keyword1 { get; set; }
        public string KeyValue { get; set; }
    }
}
