//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public System.Guid OperatorUID { get; set; }
        public string Operator1 { get; set; }
        public int AllowRights { get; set; }
        public int DenyRights { get; set; }
        public System.DateTime FirstLoginUtc { get; set; }
        public System.DateTime LastCheckinUtc { get; set; }
    }
}
