//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodForestConversion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressIndicatorArchive
    {
        public long ArchiveID { get; set; }
        public System.Guid IndicatorUID { get; set; }
        public System.Guid InstanceUID { get; set; }
        public System.Guid StepInstanceUID { get; set; }
        public byte IndicatorIndex { get; set; }
        public byte ProgressStatus { get; set; }
        public byte PercentComplete { get; set; }
        public bool ShowProgressBar { get; set; }
        public string ProgressMessage { get; set; }
        public System.DateTime LastModifiedUtc { get; set; }
        public System.DateTime SpawnedAtUtc { get; set; }
        public System.DateTime ArchivedAtUtc { get; set; }
    }
}
